services:

  front-frame:
    image: nginx:latest
    # ports:
    #   - "51000:80"
    volumes:
      - ./front-frame/app:/usr/share/nginx/html:ro
      - ./front-frame/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - prod_network

  front-frame-auth:
    image: nginx:latest
    ports:
      - "51001:80"
    volumes:
      - ./front-frame/nginx-auth.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front-frame/htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - front-frame
    networks:
      - prod_network

networks:
  prod_network:
    external: true